language: cpp
compiler:
  - gcc
script: cmake . && make

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost1.48-dev libboost-date-time1.48-dev libboost-system1.48-dev libboost-thread1.48-dev libboost-random1.48-dev libboost-regex1.48-dev libboost-program-options1.48-dev libqt4-dev cmake
